import { writeFileSync, mkdirSync } from "fs";
import type { RouteManifest } from "./types.ts";
import { currentBase } from "./appBase.ts";
import { toPosix } from "./paths.ts";

/**
 * The pattern the *client* router matches against. It sees real browser URLs, so
 * under a BASE_PATH mount the table has to carry the prefix — that is what lets
 * `findMatch` take `location.pathname` and an anchor's href exactly as they are,
 * with no conversion anywhere in the navigation path.
 *
 * `serverRoutes` deliberately does not get this: the server strips the prefix at
 * the edge of the request, so hooks, `load()` and `event.url.pathname` keep
 * seeing app-space paths and app code never has to know it is mounted.
 *
 * The root route maps to the bare base (`/sso`, not `/sso/`) so it agrees with
 * the URL a browser actually lands on.
 */
function clientPattern(pattern: string): string {
	const base = currentBase();
	if (!base) return pattern;
	return pattern === "/" ? base : base + pattern;
}

// ─── Route File Generator ─────────────────────────────────
// Generates .bosia/routes.ts — ONE file with three exports:
//   clientRoutes  — used by client hydrator (page + layout lazy imports)
//   serverRoutes  — used by SSR renderer (+ pageServer + layoutServers)
//   apiRoutes     — used by API handler

function routePriority(pattern: string): number {
	if (!pattern.includes("[")) return 0; // exact
	if (!pattern.includes("[...")) return 1; // dynamic
	return 2; // catch-all
}

function sortRoutes<T extends { pattern: string }>(routes: T[]): T[] {
	return [...routes].sort((a, b) => {
		const pa = routePriority(a.pattern);
		const pb = routePriority(b.pattern);
		if (pa !== pb) return pa - pb;
		// same tier: more segments first, then alphabetical
		const sa = a.pattern.split("/").length;
		const sb = b.pattern.split("/").length;
		if (sa !== sb) return sb - sa;
		return a.pattern.localeCompare(b.pattern);
	});
}

export function generateRoutesFile(manifest: RouteManifest): void {
	const lines: string[] = ["// AUTO-GENERATED by bosia build — do not edit\n", ONCE_HELPER];

	const pages = sortRoutes(manifest.pages);
	const apis = sortRoutes(manifest.apis);

	// clientRoutes
	lines.push("export const clientRoutes: Array<{");
	lines.push("  pattern: string;");
	lines.push("  page: () => Promise<any>;");
	lines.push("  layouts: (() => Promise<any>)[];");
	lines.push("  errorPages: { loader: () => Promise<any>; depth: number }[];");
	lines.push("  hasServerData: boolean;");
	lines.push('  trailingSlash: "never" | "always" | "ignore";');
	// Stable ids per node, used by the client loader cache to detect whether
	// a layout/page at a given depth is the same as last nav's (skip) or new
	// (re-run). One id per layout in order, plus an optional page id.
	lines.push("  pageId: string | null;");
	lines.push("  layoutIds: (string | null)[];");
	lines.push("  loading: (() => Promise<any>) | null;");
	lines.push("  layoutPaths: string[];");
	lines.push("  prerender: boolean;");
	lines.push("}> = [");
	for (const r of pages) {
		const layoutImports = r.layouts
			.map((l) => `() => import(${JSON.stringify(toImportPath(l))})`)
			.join(", ");
		const errorPageImports = r.errorPages
			.map(
				(ep) =>
					`{ loader: () => import(${JSON.stringify(toImportPath(ep.path))}), depth: ${ep.depth} }`,
			)
			.join(", ");
		const hasServerData = !!(r.pageServer || r.layoutServers.length > 0);
		const pageId = r.pageServer ? JSON.stringify(r.pageServer) : "null";
		// Map +layout.server.ts paths to their layout depth, leaving nulls for
		// layouts that have no server loader. Length matches layouts.length so
		// client cache can index by depth.
		const layoutIdByDepth: (string | null)[] = new Array(r.layouts.length).fill(null);
		for (const ls of r.layoutServers) layoutIdByDepth[ls.depth] = ls.path;
		const layoutIds = layoutIdByDepth
			.map((id) => (id === null ? "null" : JSON.stringify(id)))
			.join(", ");
		lines.push("  {");
		lines.push(`    pattern: ${JSON.stringify(clientPattern(r.pattern))},`);
		lines.push(`    page: () => import(${JSON.stringify(toImportPath(r.page))}),`);
		lines.push(`    layouts: [${layoutImports}],`);
		lines.push(`    errorPages: [${errorPageImports}],`);
		lines.push(`    hasServerData: ${hasServerData},`);
		lines.push(`    trailingSlash: ${JSON.stringify(r.trailingSlash)},`);
		lines.push(`    pageId: ${pageId},`);
		lines.push(`    layoutIds: [${layoutIds}],`);
		lines.push(
			`    loading: ${r.loading ? `() => import(${JSON.stringify(toImportPath(r.loading))})` : "null"},`,
		);
		lines.push(`    layoutPaths: ${JSON.stringify(r.layouts)},`);
		lines.push(`    prerender: ${r.prerender},`);
		lines.push("  },");
	}
	lines.push("];\n");

	// serverRoutes
	lines.push("export const serverRoutes: Array<{");
	lines.push("  pattern: string;");
	lines.push("  pageModule: () => Promise<any>;");
	lines.push("  layoutModules: (() => Promise<any>)[];");
	lines.push("  pageServer: (() => Promise<any>) | null;");
	lines.push("  layoutServers: { loader: () => Promise<any>; depth: number }[];");
	lines.push("  errorPages: { loader: () => Promise<any>; depth: number }[];");
	lines.push('  trailingSlash: "never" | "always" | "ignore";');
	lines.push("  cache: boolean | null;");
	lines.push("}> = [");
	for (const r of pages) {
		const layoutImports = r.layouts.map((l) => serverImport(l)).join(", ");
		const layoutServerImports = r.layoutServers
			.map((ls) => `{ loader: ${serverImport(ls.path)}, depth: ${ls.depth} }`)
			.join(", ");
		const errorPageImports = r.errorPages
			.map((ep) => `{ loader: ${serverImport(ep.path)}, depth: ${ep.depth} }`)
			.join(", ");
		lines.push("  {");
		lines.push(`    pattern: ${JSON.stringify(r.pattern)},`);
		lines.push(`    pageModule: ${serverImport(r.page)},`);
		lines.push(`    layoutModules: [${layoutImports}],`);
		lines.push(`    pageServer: ${r.pageServer ? serverImport(r.pageServer) : "null"},`);
		lines.push(`    layoutServers: [${layoutServerImports}],`);
		lines.push(`    errorPages: [${errorPageImports}],`);
		lines.push(`    trailingSlash: ${JSON.stringify(r.trailingSlash)},`);
		lines.push(`    cache: ${JSON.stringify(r.cache ?? null)},`);
		lines.push("  },");
	}
	lines.push("];\n");

	// apiRoutes
	lines.push("export const apiRoutes: Array<{");
	lines.push("  pattern: string;");
	lines.push("  module: () => Promise<any>;");
	lines.push("}> = [");
	for (const r of apis) {
		lines.push("  {");
		lines.push(`    pattern: ${JSON.stringify(r.pattern)},`);
		lines.push(`    module: ${serverImport(r.server)},`);
		lines.push("  },");
	}
	lines.push("];\n");

	// errorPage
	const ep = manifest.errorPage;
	lines.push(
		`export const errorPage: (() => Promise<any>) | null = ${ep ? serverImport(ep) : "null"};\n`,
	);

	mkdirSync(".bosia", { recursive: true });
	writeFileSync(".bosia/routes.ts", lines.join("\n"));

	// Generate client-only routes file (no server imports that could pull in Node builtins)
	generateClientRoutesFile(pages, manifest.errorPage);

	const pagePatterns = pages.map((p) => p.pattern).join(", ") || "(none)";
	console.log(`✅ Routes generated: .bosia/routes.ts`);
	console.log(`   Found ${pages.length} page route(s): ${pagePatterns}`);
}

// ─── Client-only routes file ─────────────────────────────
// Separate file with only clientRoutes + errorPage to prevent
// the browser bundler from following server-side dynamic imports
// (e.g. +page.server.ts → drizzle-orm → postgres → Node builtins).

function generateClientRoutesFile(
	pages: RouteManifest["pages"],
	errorPage: RouteManifest["errorPage"],
): void {
	const lines: string[] = [
		"// AUTO-GENERATED by bosia build — client-only routes (no server imports)\n",
	];

	lines.push("export const clientRoutes: Array<{");
	lines.push("  pattern: string;");
	lines.push("  page: () => Promise<any>;");
	lines.push("  layouts: (() => Promise<any>)[];");
	lines.push("  errorPages: { loader: () => Promise<any>; depth: number }[];");
	lines.push("  hasServerData: boolean;");
	lines.push('  trailingSlash: "never" | "always" | "ignore";');
	lines.push("  pageId: string | null;");
	lines.push("  layoutIds: (string | null)[];");
	lines.push("  loading: (() => Promise<any>) | null;");
	lines.push("  layoutPaths: string[];");
	lines.push("  prerender: boolean;");
	lines.push("}> = [");
	for (const r of pages) {
		const layoutImports = r.layouts
			.map((l) => `() => import(${JSON.stringify(toImportPath(l))})`)
			.join(", ");
		const errorPageImports = r.errorPages
			.map(
				(ep) =>
					`{ loader: () => import(${JSON.stringify(toImportPath(ep.path))}), depth: ${ep.depth} }`,
			)
			.join(", ");
		const hasServerData = !!(r.pageServer || r.layoutServers.length > 0);
		const pageId = r.pageServer ? JSON.stringify(r.pageServer) : "null";
		const layoutIdByDepth: (string | null)[] = new Array(r.layouts.length).fill(null);
		for (const ls of r.layoutServers) layoutIdByDepth[ls.depth] = ls.path;
		const layoutIds = layoutIdByDepth
			.map((id) => (id === null ? "null" : JSON.stringify(id)))
			.join(", ");
		lines.push("  {");
		lines.push(`    pattern: ${JSON.stringify(clientPattern(r.pattern))},`);
		lines.push(`    page: () => import(${JSON.stringify(toImportPath(r.page))}),`);
		lines.push(`    layouts: [${layoutImports}],`);
		lines.push(`    errorPages: [${errorPageImports}],`);
		lines.push(`    hasServerData: ${hasServerData},`);
		lines.push(`    trailingSlash: ${JSON.stringify(r.trailingSlash)},`);
		lines.push(`    pageId: ${pageId},`);
		lines.push(`    layoutIds: [${layoutIds}],`);
		lines.push(
			`    loading: ${r.loading ? `() => import(${JSON.stringify(toImportPath(r.loading))})` : "null"},`,
		);
		lines.push(`    layoutPaths: ${JSON.stringify(r.layouts)},`);
		lines.push(`    prerender: ${r.prerender},`);
		lines.push("  },");
	}
	lines.push("];\n");

	const ep = errorPage;
	lines.push(
		`export const errorPage: (() => Promise<any>) | null = ${
			ep ? `() => import(${JSON.stringify(toImportPath(ep))})` : "null"
		};\n`,
	);

	writeFileSync(".bosia/routes.client.ts", lines.join("\n"));
}

// The renderer calls these thunks several times per request (metadata, load,
// render), and a repeated `import()` still resolves the specifier each time even
// though the module is cached — ~8% of CPU on an uncached SSR request. Each thunk
// keeps its first promise instead. A rejected import is dropped, so the next
// request retries it rather than replaying the failure forever.
const ONCE_HELPER = `function once<T>(load: () => Promise<T>): () => Promise<T> {
  let p: Promise<T> | undefined;
  return () =>
    (p ??= load().catch((err) => {
      p = undefined;
      throw err;
    }));
}
`;

/** A memoized server-side import thunk for `src/routes/<routePath>`. */
function serverImport(routePath: string): string {
	return `once(() => import(${JSON.stringify(toImportPath(routePath))}))`;
}

// Import path from .bosia/routes.ts to src/routes/<routePath>
function toImportPath(routePath: string): string {
	return "../src/routes/" + toPosix(routePath);
}
